build test 6

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -3,8 +3,8 @@ on: push
 
 env:
   REGISTRY: ghcr.io
-  IMAGE_NAME: pranludi/catalog-service
   VERSION: latest
+  IMAGE_NAME: ghcr.io/pranludi/catalog-service:${{ env.VERSION }}
 
 jobs:
   build:
@@ -15,9 +15,9 @@ jobs:
       security-events: write
     steps:
       - name: Checkout source code
-        uses: actions/checkout@v4.1.1
+        uses: actions/checkout@v4
       - name: Set up JDK
-        uses: actions/setup-java@v4.7.1
+        uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 21
@@ -61,20 +61,20 @@ jobs:
         run: |
           chmod +x gradlew
           ./gradlew bootBuildImage \
-            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-      - name: OCI image vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          fail-build: false
-          severity-cutoff: high
-          output-format: 'sarif'
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
+            --imageName ${{ env.IMAGE_NAME }}
+#      - name: OCI image vulnerability scanning
+#        uses: anchore/scan-action@v3
+#        id: scan
+#        with:
+#          image: ${{ env.IMAGE_NAME }}
+#          fail-build: false
+#          severity-cutoff: high
+#          output-format: 'sarif'
+#      - name: Upload vulnerability report
+#        uses: github/codeql-action/upload-sarif@v3
+#        if: success() || failure()
+#        with:
+#          sarif_file: ${{ steps.scan.outputs.sarif }}
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -82,4 +82,4 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Publish container image
-        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+        run: docker push ${{ env.IMAGE_NAME }}
